name: Publish Docker image

on:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:
    inputs:
      es_version:
        description: "Elasticsearch version"
        required: true
        default: "8.15.3"

jobs:
  build-and-push:
    if: github.repository_owner == 'openmrs'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      ES_VERSION: ${{ github.event.inputs.es_version || '8.15.3' }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca11a51296c28c638c5d43e2f8f2bada123e0b # v3.10.0

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@369eb591f429131d8269d8c71a16a4c6fbb0e3c9 # v5.7.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ env.ES_VERSION }}
            type=raw,value=latest,enable=${{ env.ES_VERSION == '8.15.3' }}

      - name: Build and push
        uses: docker/build-push-action@b32b51a8b6527d0b0c8d3eac99e6d250acb39f37 # v6.14.0
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ES_VERSION=${{ env.ES_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
